### ISSUE TITLE
How do I use Reflux?

### ISSUE THREAD

**Issue by transcental** [frissyn/Reflux#9]
I was looking at the docs and files, but what I couldn't see anywhere is *how* to install and use Reflux in the browser to change the theme. 

I know that a PyPi package won't do that. Is there a Chrome extension or something that goes with this?

**Comment by BD103** [comment]
You can view the official template [here](https://replit.com/@reflux/template?v=1). What you need are two files, one the Python script and one a YAML file of values.

```python
# main.py
import reflux

theme = reflux.Theme("theme.yaml")
# Output CSS to file
code = theme.to_stylesheet("theme.css")
```

```yaml
# Default values at
# https://github.com/frissyn/Reflux/blob/master/docs/Tokens.yaml
Meta:
  name: Your Theme Name
  description: Theme description
Styles:
  root:
    ...
  tokens:
    ...
```

This will output your CSS to theme.css. You can then use a [CSS injector](https://mcdlr.com/css-inject/) to create the bookmarklet necessary. Reflux has this functionality built-in, but it doesn't work without integration with the API.

@frissyn Are there any plans for outputting the engine without needing a token?
